TESTCASES: Fixed a typo in test executor
Signed-off-by: Juergen Christ <jchrist@linux.ibm.com>

diff --git a/testcases/ock_tests.sh.in b/testcases/ock_tests.sh.in
--- a/testcases/ock_tests.sh.in
+++ b/testcases/ock_tests.sh.in
@@ -253,7 +253,7 @@ run_tests()
         $j -slot $1 $NO_STOP 2>&1
         RES=$?
 		if [ $RES -ne 0 ]; then
-			echo "ERROR: Testcase $i failed to execute."
+			echo "ERROR: Testcase $j failed to execute."
 			exit $RES
 		fi
     done
@@ -292,9 +292,9 @@ main_script()
 
     for i in $SLOT; do (
         echo "********** Testing Slot $i **********"
-        check_slot $i || { echo "SKIPPING slot $i"; continue; }
+        check_slot $i || { echo "SKIPPING slot $i"; exit; }
         if [ $NONEED_TOKEN_INIT -eq 0 ]; then
-            init_slot $i || { echo "SKIPPING slot $i"; continue; }
+            init_slot $i || { echo "SKIPPING slot $i"; exit; }
         fi
         if [ "$LOGFILE" = "1" ]; then
             echo "test output for slot $i stored in log-slot_$i.txt"
