Check return code of each test on ock_tests.sh
Exit with error if the return code of the specific estcase executed
by ock_tests.sh is not equal to zero.

Signed-off-by: Paulo Vital <pvital@linux.vnet.ibm.com>

diff --git a/testcases/ock_tests.sh.in b/testcases/ock_tests.sh.in
--- a/testcases/ock_tests.sh.in
+++ b/testcases/ock_tests.sh.in
@@ -240,6 +240,11 @@ run_tests()
     for i in $( ls -U $OCK_TESTS ); do
         echo "** Now executing '$i'"
         $i -slot $1 $NO_STOP 2>&1
+        RES=$?
+		if [ $RES -ne 0 ]; then
+			echo "ERROR: Testcase $i failed to execute."
+			exit $RES
+		fi
     done
 }
 
